name: build-pdf
on: [push]
jobs:
  compile-with-pdflatex:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r Pygments
      
      - name: get TexLive
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: source.tex
          working_directory: latex
          latexmk_shell_escape: true

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: latex/source.pdf
          
          
  
  
