name: build-pdf
on: [push]
jobs:
  compile-with-pdflatex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install Pygments

      - uses: actions/upload-artifact@v4
        with:
          name: source-pdf
          path: latex/source.tex

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "latex/source.tex"
          tag: latest
          makeLatest: true
          
          
  
  
